const countryList = {
    AED: "AE",
    AFN: "AF",
    XCD: "AG",
    ALL: "AL",
    AMD: "AM",
    ANG: "AN",
    AOA: "AO",
    AQD: "AQ",
    ARS: "AR",
    AUD: "AU",
    AZN: "AZ",
    BAM: "BA",
    BBD: "BB",
    BDT: "BD",
    XOF: "BE",
    BGN: "BG",
    BHD: "BH",
    BIF: "BI",
    BMD: "BM",
    BND: "BN",
    BOB: "BO",
    BRL: "BR",
    BSD: "BS",
    NOK: "BV",
    BWP: "BW",
    BYR: "BY",
    BZD: "BZ",
    CAD: "CA",
    CDF: "CD",
    XAF: "CF",
    CHF: "CH",
    CLP: "CL",
    CNY: "CN",
    COP: "CO",
    CRC: "CR",
    CUP: "CU",
    CVE: "CV",
    CYP: "CY",
    CZK: "CZ",
    DJF: "DJ",
    DKK: "DK",
    DOP: "DO",
    DZD: "DZ",
    ECS: "EC",
    EEK: "EE",
    EGP: "EG",
    ETB: "ET",
    EUR: "FR",
    FJD: "FJ",
    FKP: "FK",
    GBP: "GB",
    GEL: "GE",
    GGP: "GG",
    GHS: "GH",
    GIP: "GI",
    GMD: "GM",
    GNF: "GN",
    GTQ: "GT",
    GYD: "GY",
    HKD: "HK",
    HNL: "HN",
    HRK: "HR",
    HTG: "HT",
    HUF: "HU",
    IDR: "ID",
    ILS: "IL",
    INR: "IN",
    IQD: "IQ",
    IRR: "IR",
    ISK: "IS",
    JMD: "JM",
    JOD: "JO",
    JPY: "JP",
    KES: "KE",
    KGS: "KG",
    KHR: "KH",
    KMF: "KM",
    KPW: "KP",
    KRW: "KR",
    KWD: "KW",
    KYD: "KY",
    KZT: "KZ",
    LAK: "LA",
    LBP: "LB",
    LKR: "LK",
    LRD: "LR",
    LSL: "LS",
    LTL: "LT",
    LVL: "LV",
    LYD: "LY",
    MAD: "MA",
    MDL: "MD",
    MGA: "MG",
    MKD: "MK",
    MMK: "MM",
    MNT: "MN",
    MOP: "MO",
    MRO: "MR",
    MTL: "MT",
    MUR: "MU",
    MVR: "MV",
    MWK: "MW",
    MXN: "MX",
    MYR: "MY",
    MZN: "MZ",
    NAD: "NA",
    XPF: "NC",
    NGN: "NG",
    NIO: "NI",
    NPR: "NP",
    NZD: "NZ",
    OMR: "OM",
    PAB: "PA",
    PEN: "PE",
    PGK: "PG",
    PHP: "PH",
    PKR: "PK",
    PLN: "PL",
    PYG: "PY",
    QAR: "QA",
    RON: "RO",
    RSD: "RS",
    RUB: "RU",
    RWF: "RW",
    SAR: "SA",
    SBD: "SB",
    SCR: "SC",
    SDG: "SD",
    SEK: "SE",
    SGD: "SG",
    SKK: "SK",
    SLL: "SL",
    SOS: "SO",
    SRD: "SR",
    STD: "ST",
    SVC: "SV",
    SYP: "SY",
    SZL: "SZ",
    THB: "TH",
    TJS: "TJ",
    TMT: "TM",
    TND: "TN",
    TOP: "TO",
    TRY: "TR",
    TTD: "TT",
    TWD: "TW",
    TZS: "TZ",
    UAH: "UA",
    UGX: "UG",
    USD: "US",
    UYU: "UY",
    UZS: "UZ",
    VEF: "VE",
    VND: "VN",
    VUV: "VU",
    YER: "YE",
    ZAR: "ZA",
    ZMK: "ZM",
    ZWD: "ZW",
  };



// const countryList = {
//   United_Arab_Emirates: "AE",
//   Afghanistan: "AF",
//   Antigua_and_Barbuda: "AG",
//   Albania: "AL",
//   Armenia: "AM",
//   Netherlands_Antilles: "AN",
//   Angola: "AO",
//   Antarctica: "AQ",
//   Argentina: "AR",
//   Australia: "AU",
//   Azerbaijan: "AZ",
//   Bosnia_and_Herzegovina: "BA",
//   Barbados: "BB",
//   Bangladesh: "BD",
//   Benin: "BE",
//   Bulgaria: "BG",
//   Bahrain: "BH",
//   Burundi: "BI",
//   Bermuda: "BM",
//   Brunei: "BN",
//   Bolivia: "BO",
//   Brazil: "BR",
//   Bahamas: "BS",
//   Bouvet_Island: "BV",
//   Botswana: "BW",
//   Belarus: "BY",
//   Belize: "BZ",
//   Canada: "CA",
//   Congo_Kinshasa: "CD",
//   Central_African_Republic: "CF",
//   Switzerland: "CH",
//   Chile: "CL",
//   China: "CN",
//   Colombia: "CO",
//   Costa_Rica: "CR",
//   Cuba: "CU",
//   Cape_Verde: "CV",
//   Cyprus: "CY",
//   Czech_Republic: "CZ",
//   Djibouti: "DJ",
//   Denmark: "DK",
//   Dominican_Republic: "DO",
//   Algeria: "DZ",
//   Ecuador: "EC",
//   Estonia: "EE",
//   Egypt: "EG",
//   Ethiopia: "ET",
//   France: "FR",
//   Fiji: "FJ",
//   Falkland_Islands: "FK",
//   United_Kingdom: "GB",
//   Georgia: "GE",
//   Guernsey: "GG",
//   Ghana: "GH",
//   Gibraltar: "GI",
//   Gambia: "GM",
//   Guinea: "GN",
//   Guatemala: "GT",
//   Guyana: "GY",
//   Hong_Kong_SAR_China: "HK",
//   Honduras: "HN",
//   Croatia: "HR",
//   Haiti: "HT",
//   Hungary: "HU",
//   Indonesia: "ID",
//   Israel: "IL",
//   India: "IN",
//   Iraq: "IQ",
//   Iran: "IR",
//   Iceland: "IS",
//   Jamaica: "JM",
//   Jordan: "JO",
//   Japan: "JP",
//   Kenya: "KE",
//   Kyrgyzstan: "KG",
//   Cambodia: "KH",
//   Comoros: "KM",
//   North_Korea: "KP",
//   South_Korea: "KR",
//   Kuwait: "KW",
//   Cayman_Islands: "KY",
//   Kazakhstan: "KZ",
//   Laos: "LA",
//   Lebanon: "LB",
//   Sri_Lanka: "LK",
//   Liberia: "LR",
//   Lesotho: "LS",
//   Lithuania: "LT",
//   Latvia: "LV",
//   Libya: "LY",
//   Morocco: "MA",
//   Moldova: "MD",
//   Madagascar: "MG",
//   North_Macedonia: "MK",
//   Myanmar: "MM",
//   Mongolia: "MN",
//   Macau_SAR_China: "MO",
//   Mauritania: "MR",
//   Malta: "MT",
//   Mauritius: "MU",
//   Maldives: "MV",
//   Malawi: "MW",
//   Mexico: "MX",
//   Malaysia: "MY",
//   Mozambique: "MZ",
//   Namibia: "NA",
//   New_Caledonia: "NC",
//   Nigeria: "NG",
//   Nicaragua: "NI",
//   Nepal: "NP",
//   New_Zealand: "NZ",
//   Oman: "OM",
//   Panama: "PA",
//   Peru: "PE",
//   Papua_New_Guinea: "PG",
//   Philippines: "PH",
//   Pakistan: "PK",
//   Poland: "PL",
//   Paraguay: "PY",
//   Qatar: "QA",
//   Romania: "RO",
//   Serbia: "RS",
//   Russia: "RU",
//   Rwanda: "RW",
//   Saudi_Arabia: "SA",
//   Solomon_Islands: "SB",
//   Seychelles: "SC",
//   Sudan: "SD",
//   Sweden: "SE",
//   Singapore: "SG",
//   Slovakia: "SK",
//   Sierra_Leone: "SL",
//   Somalia: "SO",
//   Suriname: "SR",
//   Sao_Tome_and_Principe: "ST",
//   El_Salvador: "SV",
//   Syria: "SY",
//   Eswatini: "SZ",
//   Thailand: "TH",
//   Tajikistan: "TJ",
//   Turkmenistan: "TM",
//   Tunisia: "TN",
//   Tonga: "TO",
//   Turkey: "TR",
//   Trinidad_and_Tobago: "TT",
//   Taiwan: "TW",
//   Tanzania: "TZ",
//   Ukraine: "UA",
//   Uganda: "UG",
//   United_States: "US",
//   Uruguay: "UY",
//   Uzbekistan: "UZ",
//   Venezuela: "VE",
//   Vietnam: "VN",
//   Vanuatu: "VU",
//   Yemen: "YE",
//   South_Africa: "ZA",
//   Zambia: "ZM",
//   Zimbabwe: "ZW"
// };

// const countryList = {
//   "United Arab Emirates": "AED",
//   "Afghanistan": "AFN",
//   "Antigua and Barbuda": "XCD",
//   "Albania": "ALL",
//   "Armenia": "AMD",
//   "Netherlands Antilles": "ANG",
//   "Angola": "AOA",
//   "Antarctica": "AQD",
//   "Argentina": "ARS",
//   "Australia": "AUD",
//   "Azerbaijan": "AZN",
//   "Bosnia and Herzegovina": "BAM",
//   "Barbados": "BBD",
//   "Bangladesh": "BDT",
//   "Benin": "XOF",
//   "Bulgaria": "BGN",
//   "Bahrain": "BHD",
//   "Burundi": "BIF",
//   "Bermuda": "BMD",
//   "Brunei": "BND",
//   "Bolivia": "BOB",
//   "Brazil": "BRL",
//   "Bahamas": "BSD",
//   "Bouvet Island": "NOK",
//   "Botswana": "BWP",
//   "Belarus": "BYR",
//   "Belize": "BZD",
//   "Canada": "CAD",
//   "Congo (Kinshasa)": "CDF",
//   "Central African Republic": "XAF",
//   "Switzerland": "CHF",
//   "Chile": "CLP",
//   "China": "CNY",
//   "Colombia": "COP",
//   "Costa Rica": "CRC",
//   "Cuba": "CUP",
//   "Cape Verde": "CVE",
//   "Cyprus": "CYP",
//   "Czech Republic": "CZK",
//   "Djibouti": "DJF",
//   "Denmark": "DKK",
//   "Dominican Republic": "DOP",
//   "Algeria": "DZD",
//   "Ecuador": "ECS",
//   "Estonia": "EEK",
//   "Egypt": "EGP",
//   "Ethiopia": "ETB",
//   "France": "EUR",
//   "Fiji": "FJD",
//   "Falkland Islands": "FKP",
//   "United Kingdom": "GBP",
//   "Georgia": "GEL",
//   "Guernsey": "GGP",
//   "Ghana": "GHS",
//   "Gibraltar": "GIP",
//   "Gambia": "GMD",
//   "Guinea": "GNF",
//   "Guatemala": "GTQ",
//   "Guyana": "GYD",
//   "Hong Kong": "HKD",
//   "Honduras": "HNL",
//   "Croatia": "HRK",
//   "Haiti": "HTG",
//   "Hungary": "HUF",
//   "Indonesia": "IDR",
//   "Israel": "ILS",
//   "India": "INR",
//   "Iraq": "IQD",
//   "Iran": "IRR",
//   "Iceland": "ISK",
//   "Jamaica": "JMD",
//   "Jordan": "JOD",
//   "Japan": "JPY",
//   "Kenya": "KES",
//   "Kyrgyzstan": "KGS",
//   "Cambodia": "KHR",
//   "Comoros": "KMF",
//   "North Korea": "KPW",
//   "South Korea": "KRW",
//   "Kuwait": "KWD",
//   "Cayman Islands": "KYD",
//   "Kazakhstan": "KZT",
//   "Laos": "LAK",
//   "Lebanon": "LBP",
//   "Sri Lanka": "LKR",
//   "Liberia": "LRD",
//   "Lesotho": "LSL",
//   "Lithuania": "LTL",
//   "Latvia": "LVL",
//   "Libya": "LYD",
//   "Morocco": "MAD",
//   "Moldova": "MDL",
//   "Madagascar": "MGA",
//   "North Macedonia": "MKD",
//   "Myanmar (Burma)": "MMK",
//   "Mongolia": "MNT",
//   "Macau": "MOP",
//   "Mauritania": "MRO",
//   "Malta": "MTL",
//   "Mauritius": "MUR",
//   "Maldives": "MVR",
//   "Malawi": "MWK",
//   "Mexico": "MXN",
//   "Malaysia": "MYR",
//   "Mozambique": "MZN",
//   "Namibia": "NAD",
//   "New Caledonia": "XPF",
//   "Nigeria": "NGN",
//   "Nicaragua": "NIO",
//   "Nepal": "NPR",
//   "New Zealand": "NZD",
//   "Oman": "OMR",
//   "Panama": "PAB",
//   "Peru": "PEN",
//   "Papua New Guinea": "PGK",
//   "Philippines": "PHP",
//   "Pakistan": "PKR",
//   "Poland": "PLN",
//   "Paraguay": "PYG",
//   "Qatar": "QAR",
//   "Romania": "RON",
//   "Serbia": "RSD",
//   "Russia": "RUB",
//   "Rwanda": "RWF",
//   "Saudi Arabia": "SAR",
//   "Solomon Islands": "SBD",
//   "Seychelles": "SCR",
//   "Sudan": "SDG",
//   "Sweden": "SEK",
//   "Singapore": "SGD",
//   "Slovakia": "SKK",
//   "Sierra Leone": "SLL",
//   "Somalia": "SOS",
//   "Suriname": "SRD",
//   "Sao Tome and Principe": "STD",
//   "El Salvador": "SVC",
//   "Syria": "SYP",
//   "Eswatini": "SZL",
//   "Thailand": "THB",
//   "Tajikistan": "TJS",
//   "Turkmenistan": "TMT",
//   "Tunisia": "TND",
//   "Tonga": "TOP",
//   "Turkey": "TRY",
//   "Trinidad and Tobago": "TTD",
//   "Taiwan": "TWD",
//   "Tanzania": "TZS",
//   "Ukraine": "UAH",
//   "Uganda": "UGX",
//   "United States": "USD",
//   "Uruguay": "UYU",
//   "Uzbekistan": "UZS",
//   "Venezuela": "VEF",
//   "Vietnam": "VND",
//   "Vanuatu": "VUV",
//   "Yemen": "YER",
//   "South Africa": "ZAR",
//   "Zambia": "ZMK",
//   "Zimbabwe": "ZWD",
// };

